# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](https://github.com/ironhack-labs/lab-neural-networks/blob/master/your-code/tttboard.jpg?raw=1)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [7]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# 2. Leer el dataset
# Aquí se asume que tienes el archivo en CSV. Si el archivo original es .data, asegúrate de convertirlo o renombrar.
df = pd.read_csv("/tic-tac-toe.csv")

print("Primeras filas:")
print(df.head())
print("\nInformación general:")
print(df.info())
print("\nValores únicos por columna:")
for col in df.columns:
    print(col, "->", df[col].unique())

print("\nConteo de la variable objetivo:")
print(df['class'].value_counts())  # Nota: en este dataset la columna “class” es el target (positive/negative) :contentReference[oaicite:2]{index=2}

# 4. Convertir valores categóricos a numéricos en todas las columnas
encoder = LabelEncoder()
for col in df.columns:
    df[col] = encoder.fit_transform(df[col])

print("\nDespués de codificar:")
print(df.head())

# 5. Separar variables de entrada (X) y salida (y)
X = df.drop('class', axis=1)
y = df['class']

print("\nDimensiones de X:", X.shape)
print("Dimensión de y:", y.shape)

# 6. Normalizar los datos de entrada
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Convertir de nuevo a DataFrame para mantener nombres de columnas (opcional)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print("\nPrimeras filas de los datos escalados:")
print(X_scaled.head())

Primeras filas:
  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB
None

Valores únicos por columna:
TL -> ['x' 'o' 'b']
TM -> ['x' 'o' 'b']
TR -> ['x' 'o' 'b']
ML -> ['x' 'o' 'b']
MM -> ['o' 'b' 'x']
MR -> ['o' 'b' 'x']
BL -> ['x' 'o' 'b']
BM -> ['o' 'x' 'b']
BR -> ['o' 'x' 'b']
class -> [ True False]

Conteo de la variable objetivo:
class
True     626
False    332
Name: count, dtype: int64

Después de codificar:
   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   2   2   2   2   1   1   2   1   1      1
1   2   2   2   2   1   1   1   2   1      1
2   2   2   2   2   1   1   1   1   2      1
3   2   2   2   2   1   1   1   0   0      1
4   2   2   2   2   1   1   0   1   0      1

Dimensiones de X: (958, 9)
Dimensión de y: (958,)

Primeras filas de los datos escalados:
    TL   TM   TR   ML   MM   MR   BL   BM   BR
0  1.0  1.0  1.0  1.0  0.5  0.5  1.0  0.5  0.5
1  1.0  1.0  1.0  1.0  0.5  0.5  0.5  1.0  0.5
2  1.0  1.0  1.0  1.0  0.5  0.5  0.5  0.5  1.0
3  1.0  1.0  1.0  1.0  0.5  0.5  0.5  0.0  0.0
4  1.0  1.0  1.0  1.0  0.5  0.5  0.0  0.5  0.0

In [10]:
concrete_data = pd.read_csv('/tic-tac-toe.csv')
concrete_data.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [11]:
concrete_data.shape

(958, 10)

In [12]:
concrete_data.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [13]:
concrete_data.isnull().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [15]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'BR']] # all columns except Strength
target = concrete_data['BR'] # BR column

In [16]:
predictors.head()

  TL TM TR ML MM MR BL BM  class
0  x  x  x  x  o  o  x  o   True
1  x  x  x  x  o  o  o  x   True
2  x  x  x  x  o  o  o  o   True
3  x  x  x  x  o  o  o  b   True
4  x  x  x  x  o  o  b  o   True

In [17]:
target.head()

0    o
1    o
2    x
3    b
4    b
Name: BR, dtype: object

In [31]:
encoder = LabelEncoder()
for col in df.columns:
    df[col] = encoder.fit_transform(df[col])
X = df.drop('class', axis=1)
y = df['class']

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
print("\nPrimeras filas de los datos escalados:")
print(X_scaled.head())

Primeras filas de los datos escalados:
    TL   TM   TR   ML   MM   MR   BL   BM   BR
0  1.0  1.0  1.0  1.0  0.5  0.5  1.0  0.5  0.5
1  1.0  1.0  1.0  1.0  0.5  0.5  0.5  1.0  0.5
2  1.0  1.0  1.0  1.0  0.5  0.5  0.5  0.5  1.0
3  1.0  1.0  1.0  1.0  0.5  0.5  0.5  0.0  0.0
4  1.0  1.0  1.0  1.0  0.5  0.5  0.0  0.5  0.0

In [35]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

TypeError: Could not convert ['xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxooooooo'
 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooooobbbbbbbbbbbbbbxxxooooooxxxxxxo'
 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooobbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxoooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooooobbbbbbbbbbbbxxxxxxxxxxxxoooooooooooooooooooobbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooooobbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxoooooooooooobbbbbboooooooooooooooooooooooooooooooooobbbbbbbbbbbbxxxxxxxxxxxxxxxxxxoooooooobbbbbbbxxxxxxxxxxxxooooooooooooooooobbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooooooobbbbbbbbbbbbbbbbbxxxxxxxxoooooooooooooooooooooooooooooooooooobbbxxxxxxxxxxxxxxxxxoooobbbbbbbbxxxxxxxxxxxxooooooooooooooooobbbbbbxxxxxxxooobbbbxxxxxxoooooooooooxxxxxoxxxooox'
 'xxxxxxxxxxxxoooooooooooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxoooooooooobbbbbxxxxoooooobbxxxxxxxxooooooooooooooobbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxoooooooobbbbbbbbbxxxxxxxxxxxxxxxxxxxxooooooooobbbbbbbxxxxooooooooobbbxxxxxxxxxxxxxxxxxxxxooooooooobbbbbbbxxxxxxxxxxxoooooobbbxxxooooooooooobbbbbbbbbxxxxxxxxxxxooooooobbbbbbbbbxxxxxxooooooobbbbbbbxxxxxxxxxxxxxxxxooooooooooobbbbbbbbbbbbbbbbxxxxxxxxxoobbbxxxxxxxxxoooooooooooooobbbbbbbbbbbbbxxxxxxxxxoobbbxxxxxxxooobbooooooooobbbxxxxxooooooooobbbbbbxoooooobbbxxxxxxxxoooooooooooooooobbbbbbbbbbbbxxxxxxxxxoobbbxxxxxxxooobbxxoooooooooooobbbbbbxxxxxxxooobbxxxoobxxxxxxxxxxxxxxoooooooobbbbbbbbbbbbxxxooooooobbxxxxxxxooooobbbbbbxxxxxbbbxxxobbbxxxooooooobbxxxxxxxxxoobbbbbbxxooobxxxxxxxxxoooooooooooooooooobbbbbbbxxxxxxxxoobbxxxxxxoooooooobbbxxxxxoobxxxxxxxxxxxxxxxxxxxxxooobbbbbbbbbbbbxxoxxxxxxoooooooobbbxxxoxxxoooobxxxooooooobbxxxxxxxxxxxobbbbbxxooobxxxxxbbxxxxxxbxxooobxxxxxxbboooxxxoooxxxxxox'
 'ooooooooobbbxxxxxxxxxooooooooooooobbbbbbbbbbbbbbbbxxxoooooooooooooooobbbbbbbbbxooooobbxxxxxxxxxxxxxxxooobxxxxxxxxxxooobbbxxxxxxxxxxxoobbxxxxxxobxxxxxxxxxxxxxxooooobbbbbbbxxxxxxobxxxxxxxobxxxxxxxxxooooobbbbbbxxxxxxxobxxxxxxoooobxxxxxxoobxxoxxxxxxxxooooooobbbbbxxxxxxxobxxxxxxoxxoooooobbbxxxxxxxxxxxoxxxxxxxxoobxxxxxxoobxxxxxxxxxxoxxxxxobxxxxxxxobxxxxxxxxxxxobxxxxxxoxxxxxxxxxxxooobbxxxxxxxobbbxxxxxxxxxooobbbbxxxxxxxobxbxobxxxxxxoobxxxxxxxxooobbbxxxxxxxoooobbxxxxxxxobxbxobxxxxxxoxobobxxxxxxoobxxoxxxxxxxxxxxxobxxxxxoxxxxxxxxxxxxxxxxobxxxxxxxxxooobbbbxxxxxxxooobbxxxxxxxobxbxobxxxxxxoxobobxoxxxxxxxooobbxxxoobxxxxxxoxobobxxxoboxxxoooooooobbbxoooooobxxxooooooobbxobxooooooxbxoooooboooooxoooooxooooxoooooooooxobxooooooxbxxoooooobxoxxooobxboooxxooooooobxxxxxoooooooobbbbbxooooooxoooooobxbooooooooxxxoobbbooooooooxxoxxxxxxxxxooobbbbbbbbbxxxxxxxxxxxxbbbooxooooooxxxxxobboooxooxoooxxxboxobxooooooxbxxooooooobboxooobxboooxoooooooxooooooxboooxxxooobxoxooxooxoxxooxoxx'
 'oooooobbbooooooooobbbxxxxxxbbbbbbbxxxooooooobbbbbboooxxxooooooobbbbbboooooobbboxoobbobxxoooobbbbooobboobooooobbooooooboobxxooooobbbbxxxxoooobbxxxxxxxxoooobbbbxxobbxxoobbbxxxobbxbxxoobbbboxxxoooobbxoobbxooobbxxoobbbboxooobbooobooooobbxxxooxxxxooobbxxoobbbxoobbxxoobbbboxooobboooxooobboobxooobboobooxxoooobbbxxxoooobbxxxxxxxxxoobboxxobbxbxxoobbbboxxxoobxoobbboxooobboxxxxxxooobbxxoxxxxxxobbxxxbxxxxoobbbxxbxxxoxxxxxxxbobxoxbxxxoobxxxxxxoobbbxxbxxoxxooobbxxxoxxxxxxxxxbobxoxbxxxxxxooxbbooooobbxxxooxxxxobxxoobbbboxoobbooxooobboobxxxoobxxxxxxoobbbxxbxxxoxxooobbxxoxxxxxxxxxbobxoxbxxxxxxooxbbooxxxooobbxxxxxoobxxxxxxxxxooxbboxxxboooobxxooobbbxoooxxoooboxooxxxoobboooxbxoooooobxbxxobbxxooobxxxobboxxxboxxxxbxxxboxbxoooooobxooxxxobbooxooxxbobxoooxbxxoobbbxxxobbxxxooobbxxobbxxxxobboxxxxbboxxxxxxxobbxxbxxxxbxxbxxxbbxbxooobbbbbbxxxxxxxxxbbbxxxxxxxxxbbbxxxxxxxxxobbxxobbxxbxxboxxxxxbxxbxxoxbxoooooobxooxxxoobbooxoxxbobxoooxxxobbxboxxxxbxbxoooxooxxbooxxxxoxoxxxooooxxo'
 'xooobbooboobxooobboobxooobbxxoobbboobxxoobbbxooobbooboobxxoobbbxooobbxooobbooboxxxxxxxooxobboobboobooxxxxoobbooooxoxxxxxxxoxxxobxxobobobxxobxoooxooobbxxobxxobxxxxxxxxxxxxxobxxbxxobxbxobxxoobxxobxoxxxxxxxxxxxobxbxobxxoxobobxxxxxxxobxooboxoooobxobxoxxxxxxxxxxxxobxbxobxxoxobobxxoxxxxxxxxxoxoboboboxooxxxxbxxbxbbxxobxooboxooobbobobxxbxxbxxobxbxobxxoobobobxbxbxxoxobobxxooobbxxxxxobxobxxxbxxxxxbxxxobxxxxxxbxxobxxxoobbbxxxxxxxoobxxxoboxxbxxxxxxbxxbxxoxxxxxxobxobxxoobbbxxxxxxxxooobbxxxxxxxxobxooboxoooobooobxbxobxxoobobxooxobobobooobxxxooxxobxxxxxxbxxobxxoxxxxxobxobxxoobbbxxxxxxxxooobbxxxxxxxoxoxxxxxxobobxxxoboxooobbxxxxxxoobxxxobooooobooooobxooxxboxoxboooxoooxbooooxxxobboooobboboxxxbxoxbxxbbooboxxoobbxxbxooooxxxobboooboooooobxoxboooxooxxbooobxbxobooooooxobxxbxoooooooxobxxbxxoobxoxooxoxobxxboooxooooxbxxxbxxooxxxbxxxobbxxbxxxobbxxbxxbxxxobbxxbxxbxxoxobxxboooooxooxbxxxooxbxooooxooooxxxobbooxboooxoooxboxoooxooxxboxbxxbxxxxoxbxxooxxboxboooxxoxxxooooxxoxoxxxo'
 'oxoboboboobooxobobobooxobobobxbxoboboobxbxoboxobobobooboobxbxoboxoboboxoboboboooobobooxooxxbxbxoxboxoobooxbxoxoxoooxbboboooxobxbobboxbboobbooobooxobobobxbobboxbxxbobxbxoboxbxbxxxbobxoxbxxoboobbooobxbxboxobobbobxoxbxxooxbboxobooobboooboooooobooboooobxbxoboobobbobxoxbxxooxbboxoooxoboboboooxbboboooxooxobxobxoboobxxoxboooxobobxxxxxxxxxxxxxxxxxxxxxoboxxxxxxxxxxxxxxxxxoxobobxobobxbxboxobbxxbxbxxobboxbxobbxxoxbxobxbxobxxxxxxxobooboboooboxbxobbxxobxooxoboboxbxboobxbxobxxxxxxxoxobobxxxxxxobxxoxboooxooboxxxxxxxxxxxxxxxxxxxxxxxxxxxobooboboobboxbxobbxxoxbxooxobobxbxboobxbxobxxxxxxxoxobobxxxxxxooooxoboboxbbooboboooxobobxxxxxxoboxxxbooobxbxxoboxbbxbxbxxxoobxobxxxbbxooooxobxxbooooooooooxbxoooooooxxboxxoxoooooooooooxobxxbooxbxobxxbxxxbxxbxxooxbxoobobxoxboobbobbxxxbxxxxbxxbooxbxbxbbxbxxxxbxxxoxbxbxobbxxxbxbxxobxxoxxxxbxxobxxbxbxxobxxbxbxxbxxobxxbxbxxbxxoxoxbxbxxbxxbxxxbxxxxxxbxxxbxxxooooxobxxbooobxobxxxbbxxbxbxxooxbxooooooooxoxooooooxbxobxxbxxxxoxoxxxxxxooxooox'] to numeric

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [39]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(32, input_dim=9, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [40]:
    # build the model
model = regression_model()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [42]:
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
24/24 - 1s - 41ms/step - loss: 0.2524
Epoch 2/100
24/24 - 0s - 3ms/step - loss: 0.2117
Epoch 3/100
24/24 - 0s - 2ms/step - loss: 0.2009
Epoch 4/100
24/24 - 0s - 2ms/step - loss: 0.1935
Epoch 5/100
24/24 - 0s - 2ms/step - loss: 0.1882
Epoch 6/100
24/24 - 0s - 2ms/step - loss: 0.1843
Epoch 7/100
24/24 - 0s - 2ms/step - loss: 0.1797
Epoch 8/100
24/24 - 0s - 3ms/step - loss: 0.1742
Epoch 9/100
24/24 - 0s - 3ms/step - loss: 0.1710
Epoch 10/100
24/24 - 0s - 2ms/step - loss: 0.1693
Epoch 11/100
24/24 - 0s - 3ms/step - loss: 0.1648
Epoch 12/100
24/24 - 0s - 2ms/step - loss: 0.1605
Epoch 13/100
24/24 - 0s - 2ms/step - loss: 0.1561
Epoch 14/100
24/24 - 0s - 2ms/step - loss: 0.1532
Epoch 15/100
24/24 - 0s - 2ms/step - loss: 0.1496
Epoch 16/100
24/24 - 0s - 2ms/step - loss: 0.1482
Epoch 17/100
24/24 - 0s - 2ms/step - loss: 0.1475
Epoch 18/100
24/24 - 0s - 2ms/step - loss: 0.1377
Epoch 19/100
24/24 - 0s - 2ms/step - loss: 0.1377
Epoch 20/100
24/24 - 0s - 2ms/step - loss: 0.1351
Epoch 21/100
24/24 - 0s - 2ms/step - loss: 0.1280
Epoch 22/100
24/24 - 0s - 2ms/step - loss: 0.1245
Epoch 23/100
24/24 - 0s - 2ms/step - loss: 0.1215
Epoch 24/100
24/24 - 0s - 3ms/step - loss: 0.1191
Epoch 25/100
24/24 - 0s - 2ms/step - loss: 0.1179
Epoch 26/100
24/24 - 0s - 2ms/step - loss: 0.1153
Epoch 27/100
24/24 - 0s - 6ms/step - loss: 0.1111
Epoch 28/100
24/24 - 0s - 3ms/step - loss: 0.1098
Epoch 29/100
24/24 - 0s - 3ms/step - loss: 0.1061
Epoch 30/100
24/24 - 0s - 2ms/step - loss: 0.1027
Epoch 31/100
24/24 - 0s - 2ms/step - loss: 0.1012
Epoch 32/100
24/24 - 0s - 2ms/step - loss: 0.0985
Epoch 33/100
24/24 - 0s - 2ms/step - loss: 0.0984
Epoch 34/100
24/24 - 0s - 2ms/step - loss: 0.0973
Epoch 35/100
24/24 - 0s - 2ms/step - loss: 0.0934
Epoch 36/100
24/24 - 0s - 2ms/step - loss: 0.0916
Epoch 37/100
24/24 - 0s - 2ms/step - loss: 0.0907
Epoch 38/100
24/24 - 0s - 2ms/step - loss: 0.0909
Epoch 39/100
24/24 - 0s - 2ms/step - loss: 0.0896
Epoch 40/100
24/24 - 0s - 2ms/step - loss: 0.0851
Epoch 41/100
24/24 - 0s - 2ms/step - loss: 0.0839
Epoch 42/100
24/24 - 0s - 2ms/step - loss: 0.0831
Epoch 43/100
24/24 - 0s - 3ms/step - loss: 0.0851
Epoch 44/100
24/24 - 0s - 2ms/step - loss: 0.0826
Epoch 45/100
24/24 - 0s - 2ms/step - loss: 0.0832
Epoch 46/100
24/24 - 0s - 2ms/step - loss: 0.0791
Epoch 47/100
24/24 - 0s - 2ms/step - loss: 0.0779
Epoch 48/100
24/24 - 0s - 2ms/step - loss: 0.0789
Epoch 49/100
24/24 - 0s - 2ms/step - loss: 0.0757
Epoch 50/100
24/24 - 0s - 2ms/step - loss: 0.0743
Epoch 51/100
24/24 - 0s - 2ms/step - loss: 0.0743
Epoch 52/100
24/24 - 0s - 2ms/step - loss: 0.0751
Epoch 53/100
24/24 - 0s - 2ms/step - loss: 0.0699
Epoch 54/100
24/24 - 0s - 2ms/step - loss: 0.0710
Epoch 55/100
24/24 - 0s - 2ms/step - loss: 0.0682
Epoch 56/100
24/24 - 0s - 2ms/step - loss: 0.0668
Epoch 57/100
24/24 - 0s - 2ms/step - loss: 0.0681
Epoch 58/100
24/24 - 0s - 2ms/step - loss: 0.0719
Epoch 59/100
24/24 - 0s - 2ms/step - loss: 0.0655
Epoch 60/100
24/24 - 0s - 2ms/step - loss: 0.0644
Epoch 61/100
24/24 - 0s - 6ms/step - loss: 0.0669
Epoch 62/100
24/24 - 0s - 3ms/step - loss: 0.0655
Epoch 63/100
24/24 - 0s - 2ms/step - loss: 0.0614
Epoch 64/100
24/24 - 0s - 2ms/step - loss: 0.0607
Epoch 65/100
24/24 - 0s - 2ms/step - loss: 0.0624
Epoch 66/100
24/24 - 0s - 2ms/step - loss: 0.0602
Epoch 67/100
24/24 - 0s - 2ms/step - loss: 0.0605
Epoch 68/100
24/24 - 0s - 2ms/step - loss: 0.0566
Epoch 69/100
24/24 - 0s - 2ms/step - loss: 0.0580
Epoch 70/100
24/24 - 0s - 2ms/step - loss: 0.0571
Epoch 71/100
24/24 - 0s - 2ms/step - loss: 0.0562
Epoch 72/100
24/24 - 0s - 2ms/step - loss: 0.0550
Epoch 73/100
24/24 - 0s - 2ms/step - loss: 0.0547
Epoch 74/100
24/24 - 0s - 2ms/step - loss: 0.0539
Epoch 75/100
24/24 - 0s - 2ms/step - loss: 0.0535
Epoch 76/100
24/24 - 0s - 2ms/step - loss: 0.0525
Epoch 77/100
24/24 - 0s - 3ms/step - loss: 0.0516
Epoch 78/100
24/24 - 0s - 2ms/step - loss: 0.0518
Epoch 79/100
24/24 - 0s - 2ms/step - loss: 0.0498
Epoch 80/100
24/24 - 0s - 3ms/step - loss: 0.0509
Epoch 81/100
24/24 - 0s - 2ms/step - loss: 0.0495
Epoch 82/100
24/24 - 0s - 2ms/step - loss: 0.0496
Epoch 83/100
24/24 - 0s - 2ms/step - loss: 0.0473
Epoch 84/100
24/24 - 0s - 3ms/step - loss: 0.0463
Epoch 85/100
24/24 - 0s - 2ms/step - loss: 0.0475
Epoch 86/100
24/24 - 0s - 3ms/step - loss: 0.0462
Epoch 87/100
24/24 - 0s - 3ms/step - loss: 0.0453
Epoch 88/100
24/24 - 0s - 3ms/step - loss: 0.0458
Epoch 89/100
24/24 - 0s - 2ms/step - loss: 0.0441
Epoch 90/100
24/24 - 0s - 2ms/step - loss: 0.0444
Epoch 91/100
24/24 - 0s - 3ms/step - loss: 0.0426
Epoch 92/100
24/24 - 0s - 2ms/step - loss: 0.0424
Epoch 93/100
24/24 - 0s - 2ms/step - loss: 0.0433
Epoch 94/100
24/24 - 0s - 3ms/step - loss: 0.0416
Epoch 95/100
24/24 - 0s - 3ms/step - loss: 0.0404
Epoch 96/100
24/24 - 0s - 2ms/step - loss: 0.0411
Epoch 97/100
24/24 - 0s - 2ms/step - loss: 0.0402
Epoch 98/100
24/24 - 0s - 2ms/step - loss: 0.0392
Epoch 99/100
24/24 - 0s - 2ms/step - loss: 0.0392
Epoch 100/100
24/24 - 0s - 2ms/step - loss: 0.0392

In [36]:
# your code here
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

# 2. Dividir datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# 3. Crear modelo secuencial
model = Sequentimodel.add(Dense(32, input_dim=9, activation='relu'))al()

# 4. Agregar capas ocultas (ReLU) y capa de salida (Softmax)
model.add(Dense(32, input_dim=9, activation='relu'))  # Capa oculta 1
model.add(Dense(16, activation='relu'))               # Capa oculta 2
model.add(Dense(8, activation='relu'))                # Capa oculta 3
model.add(Dense(2, activation='softmax'))            # Capa de salida para 2 clases

# 5. Compilar modelo
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 6. Entrenar modelo
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Accuracy: {accuracy:.4f}")
print(f"Test Loss: {loss:.4f}")


model.save("tic-tac-toe.keras")

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

39/39 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6912 - loss: 0.6566 - val_accuracy: 0.6364 - val_loss: 0.6468
Epoch 2/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6689 - loss: 0.6302 - val_accuracy: 0.6364 - val_loss: 0.6462
Epoch 3/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6583 - loss: 0.6241 - val_accuracy: 0.6364 - val_loss: 0.6438
Epoch 4/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6358 - loss: 0.6300 - val_accuracy: 0.6364 - val_loss: 0.6433
Epoch 5/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6289 - loss: 0.6232 - val_accuracy: 0.6364 - val_loss: 0.6415
Epoch 6/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6558 - loss: 0.6105 - val_accuracy: 0.6364 - val_loss: 0.6358
Epoch 7/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6515 - loss: 0.5937 - val_accuracy: 0.6364 - val_loss: 0.6337
Epoch 8/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6343 - loss: 0.6006 - val_accuracy: 0.6364 - val_loss: 0.6336
Epoch 9/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6698 - loss: 0.5802 - val_accuracy: 0.6364 - val_loss: 0.6239
Epoch 10/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6924 - loss: 0.5648 - val_accuracy: 0.6494 - val_loss: 0.6179
Epoch 11/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6921 - loss: 0.5654 - val_accuracy: 0.6494 - val_loss: 0.6187
Epoch 12/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7054 - loss: 0.5563 - val_accuracy: 0.6494 - val_loss: 0.6087
Epoch 13/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7134 - loss: 0.5610 - val_accuracy: 0.6558 - val_loss: 0.6036
Epoch 14/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7140 - loss: 0.5507 - val_accuracy: 0.6753 - val_loss: 0.5998
Epoch 15/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7361 - loss: 0.5439 - val_accuracy: 0.6818 - val_loss: 0.5918
Epoch 16/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7615 - loss: 0.5160 - val_accuracy: 0.6818 - val_loss: 0.5876
Epoch 17/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7404 - loss: 0.5314 - val_accuracy: 0.6753 - val_loss: 0.5897
Epoch 18/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7740 - loss: 0.4792 - val_accuracy: 0.7273 - val_loss: 0.5752
Epoch 19/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7719 - loss: 0.4941 - val_accuracy: 0.7208 - val_loss: 0.5718
Epoch 20/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8082 - loss: 0.4792 - val_accuracy: 0.7143 - val_loss: 0.5696
Epoch 21/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8049 - loss: 0.4709 - val_accuracy: 0.7273 - val_loss: 0.5574
Epoch 22/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8076 - loss: 0.4524 - val_accuracy: 0.7273 - val_loss: 0.5557
Epoch 23/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8076 - loss: 0.4731 - val_accuracy: 0.7143 - val_loss: 0.5608
Epoch 24/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8269 - loss: 0.4324 - val_accuracy: 0.7273 - val_loss: 0.5485
Epoch 25/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8113 - loss: 0.4399 - val_accuracy: 0.7403 - val_loss: 0.5284
Epoch 26/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8324 - loss: 0.4165 - val_accuracy: 0.7338 - val_loss: 0.5390
Epoch 27/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8494 - loss: 0.3797 - val_accuracy: 0.7532 - val_loss: 0.5143
Epoch 28/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8473 - loss: 0.3901 - val_accuracy: 0.7662 - val_loss: 0.5148
Epoch 29/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8834 - loss: 0.3313 - val_accuracy: 0.7532 - val_loss: 0.5104
Epoch 30/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8708 - loss: 0.3601 - val_accuracy: 0.7727 - val_loss: 0.5084
Epoch 31/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8641 - loss: 0.3391 - val_accuracy: 0.7662 - val_loss: 0.4781
Epoch 32/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8872 - loss: 0.3309 - val_accuracy: 0.7662 - val_loss: 0.5006
Epoch 33/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8710 - loss: 0.3162 - val_accuracy: 0.7662 - val_loss: 0.4853
Epoch 34/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8933 - loss: 0.3203 - val_accuracy: 0.7727 - val_loss: 0.5133
Epoch 35/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8923 - loss: 0.3045 - val_accuracy: 0.7532 - val_loss: 0.4706
Epoch 36/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8923 - loss: 0.2964 - val_accuracy: 0.7792 - val_loss: 0.4732
Epoch 37/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9127 - loss: 0.2721 - val_accuracy: 0.7727 - val_loss: 0.4721
Epoch 38/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9110 - loss: 0.2609 - val_accuracy: 0.7532 - val_loss: 0.4648
Epoch 39/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9042 - loss: 0.2566 - val_accuracy: 0.7727 - val_loss: 0.4699
Epoch 40/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8983 - loss: 0.2446 - val_accuracy: 0.7662 - val_loss: 0.4651
Epoch 41/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9249 - loss: 0.2403 - val_accuracy: 0.7727 - val_loss: 0.4588
Epoch 42/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9189 - loss: 0.2278 - val_accuracy: 0.7792 - val_loss: 0.4634
Epoch 43/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9210 - loss: 0.2466 - val_accuracy: 0.7922 - val_loss: 0.4821
Epoch 44/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9278 - loss: 0.2102 - val_accuracy: 0.7922 - val_loss: 0.4420
Epoch 45/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9134 - loss: 0.2443 - val_accuracy: 0.7792 - val_loss: 0.4538
Epoch 46/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9280 - loss: 0.2117 - val_accuracy: 0.7922 - val_loss: 0.4435
Epoch 47/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9227 - loss: 0.2162 - val_accuracy: 0.7922 - val_loss: 0.4801
Epoch 48/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9164 - loss: 0.2192 - val_accuracy: 0.7922 - val_loss: 0.4328
Epoch 49/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9512 - loss: 0.1782 - val_accuracy: 0.8182 - val_loss: 0.4358
Epoch 50/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9505 - loss: 0.1730 - val_accuracy: 0.7792 - val_loss: 0.4628

Test Accuracy: 0.8125
Test Loss: 0.4321

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [17]:
# your code here
import numpy as np
from tensorflow.keras.models import load_model

# 1. Cargar el modelo previamente guardado
model = load_model("tic-tac-toe.keras")
print("Modelo cargado correctamente.")

# 2. Seleccionar algunas filas aleatorias del set de prueba
num_samples = 5  # cantidad de predicciones que queremos revisar
random_indices = np.random.choice(X_test.shape[0], num_samples, replace=False)
X_sample = X_test.iloc[random_indices]
y_true = y_test.iloc[random_indices]

# 3. Hacer predicciones
pred_probs = model.predict(X_sample)          # Probabilidades de cada clase
pred_classes = np.argmax(pred_probs, axis=1) # Convertir a la clase con mayor probabilidad

# 4. Mostrar resultados
for i in range(num_samples):
    print(f"\nFila #{i+1}:")
    print("Datos de entrada:", X_sample.iloc[i].values)
    print("Etiqueta real:", y_true.iloc[i])
    print("Predicción del modelo:", pred_classes[i])

Modelo cargado correctamente.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

Fila #1:
Datos de entrada: [1.  1.  0.  1.  0.5 0.  1.  0.5 0.5]
Etiqueta real: 1
Predicción del modelo: 1

Fila #2:
Datos de entrada: [0.5 0.5 0.  1.  1.  1.  0.  1.  0.5]
Etiqueta real: 1
Predicción del modelo: 1

Fila #3:
Datos de entrada: [0.  0.5 1.  0.  0.5 1.  1.  0.5 0. ]
Etiqueta real: 0
Predicción del modelo: 0

Fila #4:
Datos de entrada: [0.5 1.  1.  0.  1.  0.  1.  0.5 0.5]
Etiqueta real: 1
Predicción del modelo: 1

Fila #5:
Datos de entrada: [1.  1.  0.5 0.5 0.5 0.  0.5 1.  1. ]
Etiqueta real: 0
Predicción del modelo: 1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [19]:
# your code here

from tensorflow.keras.optimizers import Adam

# 1. Crear un nuevo modelo secuencial con más capas
improved_model = Sequential()

# Capas ocultas adicionales para mejorar aprendizaje
improved_model.add(Dense(64, input_dim=9, activation='relu'))  # Capa oculta 1
improved_model.add(Dense(32, activation='relu'))               # Capa oculta 2
improved_model.add(Dense(16, activation='relu'))               # Capa oculta 3
improved_model.add(Dense(8, activation='relu'))                # Capa oculta 4
improved_model.add(Dense(2, activation='softmax'))             # Capa de salida

# 2. Ajustar el learning rate creando un optimizador Adam personalizado
optimizer = Adam(learning_rate=0.005)  # valor por defecto es 0.001

# 3. Compilar el modelo
improved_model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 4. Entrenar el modelo con más epochs
history = improved_model.fit(
    X_train, y_train,
    epochs=100,        # más epochs para mejorar el aprendizaje
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# 5. Evaluar el modelo mejorado
loss, accuracy = improved_model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Accuracy (mejorado): {accuracy:.4f}")
print(f"Test Loss (mejorado): {loss:.4f}")

# 6. Guardar el modelo mejorado
improved_model.save("tic-tac-toe-improved.keras")
print("\nModelo mejorado guardado como 'tic-tac-toe-improved.model'")

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

39/39 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6091 - loss: 0.6458 - val_accuracy: 0.6364 - val_loss: 0.6270
Epoch 2/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6705 - loss: 0.5947 - val_accuracy: 0.6429 - val_loss: 0.6123
Epoch 3/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6512 - loss: 0.5841 - val_accuracy: 0.6558 - val_loss: 0.6755
Epoch 4/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7118 - loss: 0.5650 - val_accuracy: 0.7143 - val_loss: 0.5731
Epoch 5/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7560 - loss: 0.4923 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 6/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7629 - loss: 0.4654 - val_accuracy: 0.7662 - val_loss: 0.4889
Epoch 7/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8193 - loss: 0.3939 - val_accuracy: 0.7532 - val_loss: 0.5061
Epoch 8/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8474 - loss: 0.3614 - val_accuracy: 0.7662 - val_loss: 0.5313
Epoch 9/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8016 - loss: 0.4040 - val_accuracy: 0.7662 - val_loss: 0.4854
Epoch 10/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8623 - loss: 0.3262 - val_accuracy: 0.8377 - val_loss: 0.4072
Epoch 11/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8615 - loss: 0.2943 - val_accuracy: 0.8117 - val_loss: 0.4259
Epoch 12/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8756 - loss: 0.2831 - val_accuracy: 0.8312 - val_loss: 0.4516
Epoch 13/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8964 - loss: 0.2547 - val_accuracy: 0.8052 - val_loss: 0.4226
Epoch 14/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9143 - loss: 0.2636 - val_accuracy: 0.8052 - val_loss: 0.5197
Epoch 15/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8761 - loss: 0.2625 - val_accuracy: 0.8182 - val_loss: 0.4361
Epoch 16/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9354 - loss: 0.1719 - val_accuracy: 0.8506 - val_loss: 0.4106
Epoch 17/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9427 - loss: 0.1277 - val_accuracy: 0.8766 - val_loss: 0.3253
Epoch 18/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9564 - loss: 0.1103 - val_accuracy: 0.8312 - val_loss: 0.4044
Epoch 19/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9599 - loss: 0.1101 - val_accuracy: 0.8182 - val_loss: 0.5062
Epoch 20/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9381 - loss: 0.1528 - val_accuracy: 0.8961 - val_loss: 0.3505
Epoch 21/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9684 - loss: 0.0826 - val_accuracy: 0.8766 - val_loss: 0.3251
Epoch 22/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9704 - loss: 0.0842 - val_accuracy: 0.8831 - val_loss: 0.3337
Epoch 23/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9720 - loss: 0.0670 - val_accuracy: 0.8766 - val_loss: 0.3843
Epoch 24/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9720 - loss: 0.0989 - val_accuracy: 0.9156 - val_loss: 0.3857
Epoch 25/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9671 - loss: 0.0853 - val_accuracy: 0.8961 - val_loss: 0.3822
Epoch 26/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9838 - loss: 0.0557 - val_accuracy: 0.9026 - val_loss: 0.3351
Epoch 27/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9329 - loss: 0.2285 - val_accuracy: 0.9156 - val_loss: 0.3357
Epoch 28/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9845 - loss: 0.0527 - val_accuracy: 0.9156 - val_loss: 0.3122
Epoch 29/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9872 - loss: 0.0408 - val_accuracy: 0.8831 - val_loss: 0.5173
Epoch 30/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9926 - loss: 0.0315 - val_accuracy: 0.9221 - val_loss: 0.3753
Epoch 31/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9933 - loss: 0.0141 - val_accuracy: 0.9286 - val_loss: 0.3607
Epoch 32/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.9351 - val_loss: 0.3571
Epoch 33/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9286 - val_loss: 0.3567
Epoch 34/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.9416 - val_loss: 0.3519
Epoch 35/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9286 - val_loss: 0.3637
Epoch 36/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.8497e-04 - val_accuracy: 0.9351 - val_loss: 0.3640
Epoch 37/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.9254e-04 - val_accuracy: 0.9416 - val_loss: 0.3658
Epoch 38/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9351 - val_loss: 0.3753
Epoch 39/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.1154e-04 - val_accuracy: 0.9416 - val_loss: 0.3869
Epoch 40/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.5217e-04 - val_accuracy: 0.9351 - val_loss: 0.3792
Epoch 41/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.3768e-04 - val_accuracy: 0.9416 - val_loss: 0.3903
Epoch 42/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.5516e-04 - val_accuracy: 0.9351 - val_loss: 0.3916
Epoch 43/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.7782e-04 - val_accuracy: 0.9351 - val_loss: 0.3896
Epoch 44/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.5804e-04 - val_accuracy: 0.9351 - val_loss: 0.3927
Epoch 45/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.7515e-04 - val_accuracy: 0.9416 - val_loss: 0.4036
Epoch 46/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.0775e-04 - val_accuracy: 0.9351 - val_loss: 0.3966
Epoch 47/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.2403e-04 - val_accuracy: 0.9416 - val_loss: 0.4170
Epoch 48/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.4677e-04 - val_accuracy: 0.9286 - val_loss: 0.4085
Epoch 49/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.5567e-04 - val_accuracy: 0.9286 - val_loss: 0.4121
Epoch 50/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.8319e-04 - val_accuracy: 0.9351 - val_loss: 0.4168
Epoch 51/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.4397e-04 - val_accuracy: 0.9286 - val_loss: 0.4227
Epoch 52/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.8089e-04 - val_accuracy: 0.9286 - val_loss: 0.4232
Epoch 53/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.4053e-04 - val_accuracy: 0.9351 - val_loss: 0.4231
Epoch 54/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.5801e-04 - val_accuracy: 0.9351 - val_loss: 0.4188
Epoch 55/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.7496e-04 - val_accuracy: 0.9351 - val_loss: 0.4369
Epoch 56/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.4791e-04 - val_accuracy: 0.9351 - val_loss: 0.4335
Epoch 57/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.2207e-04 - val_accuracy: 0.9286 - val_loss: 0.4390
Epoch 58/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.0730e-04 - val_accuracy: 0.9286 - val_loss: 0.4392
Epoch 59/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6165e-04 - val_accuracy: 0.9286 - val_loss: 0.4419
Epoch 60/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.8249e-04 - val_accuracy: 0.9286 - val_loss: 0.4467
Epoch 61/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.9434e-04 - val_accuracy: 0.9286 - val_loss: 0.4462
Epoch 62/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.9472e-04 - val_accuracy: 0.9351 - val_loss: 0.4531
Epoch 63/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.8619e-04 - val_accuracy: 0.9286 - val_loss: 0.4513
Epoch 64/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.6674e-04 - val_accuracy: 0.9286 - val_loss: 0.4532
Epoch 65/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.5003e-04 - val_accuracy: 0.9286 - val_loss: 0.4577
Epoch 66/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2823e-04 - val_accuracy: 0.9286 - val_loss: 0.4597
Epoch 67/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6916e-04 - val_accuracy: 0.9351 - val_loss: 0.4641
Epoch 68/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3282e-04 - val_accuracy: 0.9286 - val_loss: 0.4641
Epoch 69/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.2862e-04 - val_accuracy: 0.9286 - val_loss: 0.4660
Epoch 70/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3064e-04 - val_accuracy: 0.9351 - val_loss: 0.4692
Epoch 71/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1572e-04 - val_accuracy: 0.9286 - val_loss: 0.4689
Epoch 72/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.2141e-04 - val_accuracy: 0.9351 - val_loss: 0.4750
Epoch 73/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1527e-04 - val_accuracy: 0.9286 - val_loss: 0.4736
Epoch 74/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0616e-04 - val_accuracy: 0.9286 - val_loss: 0.4753
Epoch 75/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.8168e-05 - val_accuracy: 0.9351 - val_loss: 0.4781
Epoch 76/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.2666e-05 - val_accuracy: 0.9351 - val_loss: 0.4821
Epoch 77/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1308e-04 - val_accuracy: 0.9351 - val_loss: 0.4831
Epoch 78/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.6065e-05 - val_accuracy: 0.9351 - val_loss: 0.4833
Epoch 79/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.5860e-05 - val_accuracy: 0.9351 - val_loss: 0.4847
Epoch 80/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.8608e-05 - val_accuracy: 0.9351 - val_loss: 0.4863
Epoch 81/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.8244e-05 - val_accuracy: 0.9351 - val_loss: 0.4925
Epoch 82/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.4548e-05 - val_accuracy: 0.9286 - val_loss: 0.4902
Epoch 83/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.0812e-05 - val_accuracy: 0.9351 - val_loss: 0.4930
Epoch 84/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 7.0978e-05 - val_accuracy: 0.9286 - val_loss: 0.4973
Epoch 85/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 7.6097e-05 - val_accuracy: 0.9351 - val_loss: 0.4966
Epoch 86/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.3717e-05 - val_accuracy: 0.9351 - val_loss: 0.4958
Epoch 87/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.8840e-05 - val_accuracy: 0.9351 - val_loss: 0.5009
Epoch 88/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 5.9203e-05 - val_accuracy: 0.9351 - val_loss: 0.5041
Epoch 89/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.4609e-05 - val_accuracy: 0.9351 - val_loss: 0.5047
Epoch 90/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.3969e-05 - val_accuracy: 0.9351 - val_loss: 0.5070
Epoch 91/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.3387e-05 - val_accuracy: 0.9416 - val_loss: 0.5073
Epoch 92/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.9195e-05 - val_accuracy: 0.9351 - val_loss: 0.5101
Epoch 93/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.9190e-05 - val_accuracy: 0.9351 - val_loss: 0.5130
Epoch 94/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.1323e-05 - val_accuracy: 0.9351 - val_loss: 0.5163
Epoch 95/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.5128e-05 - val_accuracy: 0.9351 - val_loss: 0.5198
Epoch 96/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.3286e-05 - val_accuracy: 0.9351 - val_loss: 0.5183
Epoch 97/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.9033e-05 - val_accuracy: 0.9351 - val_loss: 0.5203
Epoch 98/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.7201e-05 - val_accuracy: 0.9351 - val_loss: 0.5220
Epoch 99/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.5542e-05 - val_accuracy: 0.9351 - val_loss: 0.5255
Epoch 100/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.9171e-05 - val_accuracy: 0.9351 - val_loss: 0.5280

Test Accuracy (mejorado): 0.9479
Test Loss (mejorado): 0.5195

Modelo mejorado guardado como 'tic-tac-toe-improved.model'

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here